### ISSUE TITLE
Use Glue plugin infrastructure

### ISSUE THREAD

**Issue by astrofrog** [spacetelescope/cube-tools#7]
At the moment, the instructions tell the user to copy the contents of the glue_loader directory into ``~/.glue``, but as of Glue 0.5 it is now possible to have the package auto-register with Glue via entry-points, which will be much cleaner. If there are no objections, I'll work on this on a flight this evening.

**Comment by astrofrog** [comment]
is there a reason why some of the functionality is in ``glue_loaders`` and not in the ``cube-tools`` directory? For example, why is ``loaders.py`` not in ``cube_tools`` and imported with:

```python
from cube_tools import loaders
```

?

**Comment by astrofrog** [comment]
I think the plan should be to move all the functionality to ``cube_tools``, and we can then modify ``setup.py`` to register the plugins (I can do this)

**Comment by stscieisenhamer** [comment]
Yes. It was just because of exploration/parallel development. Feel free to fix up as desired.

**Comment by astrofrog** [comment]
@stscieisenhamer - sounds good - before I open a PR to move around files, do you have any uncommitted changes?

**Comment by stscieisenhamer** [comment]
sorry, today i have spotty coverage. no, nothing pending on commits.

**Comment by stscieisenhamer** [comment]
note: @nmearl is doing some major changing. should coordinate with him if something is going to go down here.

**Comment by stscieisenhamer** [comment]
@astrofrog just wondering if anything here has happened? We're about to try to finalize stuff by Wednesday. If not, we believe we know what this is about and will go down that path.

**Comment by astrofrog** [comment]
@stscieisenhamer - no, I was waiting to hear back from @nmearl to see if he had uncommitted changes. I can make the changes required here as soon as I get a green light :) :vertical_traffic_light:

**Comment by astrofrog** [comment]
(it would only take 15 minutes to do, but would likely conflict with any other changes)

**Comment by nmearl** [comment]
@astrofrog awesome! You're good to go on my end! :traffic_light:

**Comment by astrofrog** [comment]
Ok, thanks! Will work on it in an hour or so and it won't take long.

**Comment by astrofrog** [comment]
(working on it now)
